#!/bin/bash

# Automatically added by dh_installinit
case "$1" in
    configure)
        # Enable the service or reload the daemon
        if systemctl is-active --quiet starship-update.timer ; then
            systemctl daemon-reload
        else
            systemctl enable --now starship-update.timer
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
