#!/bin/bash

# Automatically added by dh_installinit
case "$1" in
    configure)
        # Remove the older starship-prompt package
        if dpkg-query -W -f='${Status}' starship-prompt 2>/dev/null | grep -q "install ok installed"; then
            dpkg --purge starship-prompt
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
