#!/bin/env bash

# Pre remove script for dpkg/apt
case "${1}" in
    remove|purge|upgrade)
        if systemctl is-active --quiet starship-update.timer ; then
            systemctl disable --now starship-update.timer
        fi
    ;;
    *)
        echo "prerm called with unknown argument ${1}" >&2
        exit 0
    ;;
esac
