#!/bin/env bash

set -e

poolDir="../../mls/pool/main"

test -d "${poolDir}" || { echo "Pool directory not found"; exit 1; }

test -n "${PACKAGE}" || { echo "PACKAGE not set"; exit 1; }
test -n "${VERSION}" || { echo "VERSION not set"; exit 1; }
test -n "${ARCH}" || { echo "ARCH not set"; exit 1; }

# Create the package directory if it doesn't exist
test -d "${poolDir}/s/${PACKAGE}" || mkdir -p "${poolDir}/s/${PACKAGE}"

case "${1}" in
	-f|--force)
		rm -vf ${poolDir}/s/"${PACKAGE}"/*.deb
		;;
esac

existingDeb=$(find "${poolDir}/s/${PACKAGE}/" -type f -name "*.deb")

# Exit without error if a any deb file already exists
if test -n "${existingDeb}"; then
	echo "Deb file already exists: ${existingDeb}"
	exit 0
else
	echo "Creating deb file"
	dpkg-deb --build --root-owner-group package "${poolDir}/s/${PACKAGE}/${PACKAGE}_${VERSION}_${ARCH}.deb"
fi

exit 0
